# Generated by Django 3.2.7 on 2021-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
