# Generated by Django 3.2.7 on 2021-10-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_game_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
