# Generated by Django 3.2.7 on 2021-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
    ]
